from dotenv import load_dotenv
import os

load_dotenv()

QUEUE_NAME = os.getenv('QUEUE_NAME')
BLOB_CONTAINER_NAME = os.getenv('BLOB_CONTAINER_NAME')
BLOB_CONNECTION_STRING = os.getenv('BLOB_CONNECTION_STRING')
MONGODB_CONNECTION_STRING = os.getenv('MONGODB_CONNECTION_STRING')
MONGODB_DB_NAME = os.getenv('MONGODB_DB_NAME')
MONGODB_COLLECTION_NAME = os.getenv('MONGODB_COLLECTION_NAME')